# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3859d8624e768db838c2968168e16ea699a66578698b8b594a69fde04222241056738e7f5348bc3b9c515a657d3e1b6ef793acbb3a42b0486464f86d06001240

test:
  secret_key_base: f82adc8044e6f8a4e8db1920e9a8819c6f20564bbaeac06d1921d9b5cfe184626458b13ba03dc0c354363959a0180cd5043575ea8fefd3d9e2143af2665ab44c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
